### ISSUE TITLE
how to use it with fragment

### ISSUE THREAD

**Issue by TheReprator** [Iteo/AndroidCleanUITests#2]
First thanks for this sort of detailed testing with respect to activity.

Could you please, provide me an example with fragments?

Regards,
Vikram Singh

**Comment by fadzlitown** [comment]
Looking forward to test in fragment

**Comment by TheReprator** [comment]
@fadzlitown  you can reference it from here: https://github.com/TheReprator/Wipro/tree/master/appModules/factList/src/androidTest/kotlin/reprator/wipro/factlist/test

**Comment by tomkad99** [comment]
@TheReprator Thank you for your example, unfortunately this repository is single shot and not intended to be extended sorry for that.

**Comment by TheReprator** [comment]
@tomkad99 i didn't get what you want to convey? Could you please elaborate further

**Comment by tomkad99** [comment]
@TheReprator Just to say that I don't have resources (time, people) to improve this repo in future, just that ;)

**Comment by TheReprator** [comment]
@tomkad99 no issue, you had already done a funtastic job with this repository.
